// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgjRfmcdkfVvP8BU09NX1J9sWEh0WOCAU',
    appId: '1:1007807471132:web:b9ce8aa328777e490349d9',
    messagingSenderId: '1007807471132',
    projectId: 'compare-app-eca2a',
    authDomain: 'compare-app-eca2a.firebaseapp.com',
    storageBucket: 'compare-app-eca2a.appspot.com',
    measurementId: 'G-FD4EN7NHD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEo-RrE8cVucDXomugM8nt3i_lDOHfemk',
    appId: '1:1007807471132:android:0f6dd3a3edbd00cd0349d9',
    messagingSenderId: '1007807471132',
    projectId: 'compare-app-eca2a',
    storageBucket: 'compare-app-eca2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wUgWCCloiJLClFfqbJp5MzafwRhW3eg',
    appId: '1:1007807471132:ios:a59401bcb26533600349d9',
    messagingSenderId: '1007807471132',
    projectId: 'compare-app-eca2a',
    storageBucket: 'compare-app-eca2a.appspot.com',
    iosClientId: '1007807471132-hg91quuam14sj2hrbe9gl1rqsctsbije.apps.googleusercontent.com',
    iosBundleId: 'com.example.compareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1wUgWCCloiJLClFfqbJp5MzafwRhW3eg',
    appId: '1:1007807471132:ios:fbd91989871358b60349d9',
    messagingSenderId: '1007807471132',
    projectId: 'compare-app-eca2a',
    storageBucket: 'compare-app-eca2a.appspot.com',
    iosClientId: '1007807471132-koepvnmjv8avm76ljpdh37h7auq7oflp.apps.googleusercontent.com',
    iosBundleId: 'com.example.compareApp.RunnerTests',
  );
}
